image: golang:1.7.3

before_script:
#    - export GO_PROJECT_PATH="$GOPATH/src/gitlab.com/$CI_PROJECT_NAMESPACE"
#    - echo $GO_PROJECT_PATH
#    - mkdir -p $GO_PROJECT_PATH
#    - ln -s $(pwd) $GO_PROJECT_PATH
#    - export GO_PROJECT_PATH="$GO_PROJECT_PATH/$CI_PROJECT_NAME"
#    - echo $GO_PROJECT_PATH
#    - cd $GO_PROJECT_PATH
#    - ls $GO_PROJECT_PATH

stages:
    - build
    - deploy
#    - verify
#    - style

go_build:
    stage: build
    script:
        - go get -u github.com/constabulary/gb/...
        - export GOPATH="/builds/basharov/DomioApi"
        - go get -u github.com/constabulary/gb/...

        - go get -u github.com/dgrijalva/jwt-go
        - go get -u github.com/aws/aws-sdk-go/aws
        - go get -u github.com/go-ini/ini
        - go get -u github.com/jmespath/go-jmespath
        - go get -u github.com/fatih/color
        - go get -u github.com/gorilla/mux
        - go get -u github.com/jmoiron/sqlx
        - go get -u github.com/lib/pq
        - go get -u github.com/stripe/stripe-go
        - go get -u golang.org/x/crypto/bcrypt

        - export GOPATH="/builds/basharov/DomioApi"
        - gb build domio

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
    - ssh $DEPLOY_STAGING_IP "git clone git@gitlab.com:basharov/DomioApi.git ~/domioapi; cd ~/domioapi"
    - ./install.sh
  environment:
    name: staging
    url: https://domainsforrent.com
  only:
  - master

#go_test:
#    stage: verify
#    script:
#        - go test -race -cover $(go list ./... | grep -v "vendor")

#go_vet:
#    stage: verify
#    script:
#        - go vet $(go list ./... | grep -v "vendor")

#staticcheck:
#    stage: verify
#    script:
#        - go get -u honnef.co/go/staticcheck/cmd/staticcheck
#        - staticcheck $(go list ./... | grep -v "vendor")

#golint:
#    stage: style
#    script:
#        - go get -u github.com/golang/lint/golint
#        - out=$(golint $(go list ./... | grep -v "vendor"))
#        - if [ "$out" ]; then echo "$out"; exit 1; fi

#gosimple:
#    stage: style
#    script:
#        - go get -u honnef.co/go/simple/cmd/gosimple
#        - gosimple $(go list ./... | grep -v "vendor")