#!/usr/bin/env bash
export AWS_ACCESS_KEY_ID=AKIAJMMKIJN7KUGLXA3Q
export AWS_SECRET_ACCESS_KEY=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
export DOMIO_DB_USER=postgres
export DOMIO_DB_PASSWORD=postgres
export DOMIO_DB_NAME=domio_dev